stages:
  - build
  - deploy
variables:
  IMAGE_NAME: "hermsi/ark-server"

services:
  - docker:dind

image: docker:20

before_script:
  - apk add --no-cache w3m curl jq gawk grep bash
  - export ARK_TOOLS_VERSION="$(w3m -dump https://github.com/FezVrasta/ark-server-tools/releases | grep -m1 -A2 -i "Latest release" | grep -i "v" | awk '{print $2}' | tr -d "v")"
  - find . -name "*.sh" -print0 | xargs -0 -r -n1 bash -n
  - export TIMESTAMP="$(date +%s)"

build:docker:
  stage: build
  script:
    - >
      docker build
      --no-cache
      --quiet
      --pull
      --build-arg ARK_TOOLS_VERSION="${ARK_TOOLS_VERSION}"
      --tag "${IMAGE_NAME}:tools-${ARK_TOOLS_VERSION}"
      --tag "${IMAGE_NAME}:latest"
      --tag "${IMAGE_NAME}:latest-${TIMESTAMP}"
      --file "${CI_PROJECT_DIR}/Dockerfile"
      "${CI_PROJECT_DIR}"
  except:
    - master

deploy:docker:
  stage: deploy
  script:
    - >
      docker build
      --no-cache
      --quiet
      --pull
      --build-arg ARK_TOOLS_VERSION="${ARK_TOOLS_VERSION}"
      --tag "${IMAGE_NAME}:tools-${ARK_TOOLS_VERSION}"
      --tag "${IMAGE_NAME}:latest"
      --tag "${IMAGE_NAME}:latest-${TIMESTAMP}"
      --file "${CI_PROJECT_DIR}/Dockerfile"
      "${CI_PROJECT_DIR}"
  after_script:
    - docker login -u hermsi -p"${DOCKER_HUB_TOKEN}"
    - docker push "${IMAGE_NAME}:tools-${ARK_TOOLS_VERSION}"
    - docker push "${IMAGE_NAME}:latest"
    - docker push "${IMAGE_NAME}:latest-${TIMESTAMP}"
  only:
    - master